user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /home

events:
    resource: "@EventsBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
